# Understanding the Data

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
import os
os.getcwd()

'c:\\Users\\rondu\\Desktop\\Dev1\\python-data-cleaning\\notebooks'

In [19]:
fight_air = pd.read_csv(r"..\data\fighter_aircraft_dataset_v7.csv")
fight_air.head()

,Aircraft,Manufacturer,Country,Generation,Role,First_Flight,In_Service,Max_Speed_kmh,Supercruise_kmh,Service_Ceiling_m,...,EW_Score,Combat_Kills,Combat_Losses_AirToAir,Combat_Record_Status,Kill_Loss_Ratio,Combat_Kills_A2A,Combat_Losses_A2A,Combat_Status,Kill_Ratio,Combat_Sorties_Estimated
0,F-22A Raptor,Lockheed Martin,USA,5,Air Superiority,1997,2005,2130,1810,15000,...,0.95,0,0,Limited,0.0,0,0,Limited,NaN,2500
1,F-35A Lightning II,Lockheed Martin,USA,5,Multirole,2006,2016,1960,0,15240,...,1.00,0,0,Limited,0.0,0,0,Limited,1.0,8000
2,Su-57 Felon,Sukhoi,Russia,5,Multirole,2010,2020,2135,1400,20000,...,0.75,1,0,NaN,0.0,0,0,Limited,NaN,500
3,F-15C Eagle,Boeing,USA,4,Air Superiority,1972,1976,2655,0,20000,...,0.35,104,0,Extensive,104.0,104,0,Extensive,104.0,50000
4,F-15EX Eagle II,Boeing,USA,4.5,Multirole,2021,2024,2655,0,20000,...,0.70,0,0,NaN,0.0,0,0,NaN,NaN,0

In [20]:
fight_air.tail()

,Aircraft,Manufacturer,Country,Generation,Role,First_Flight,In_Service,Max_Speed_kmh,Supercruise_kmh,Service_Ceiling_m,...,EW_Score,Combat_Kills,Combat_Losses_AirToAir,Combat_Record_Status,Kill_Loss_Ratio,Combat_Kills_A2A,Combat_Losses_A2A,Combat_Status,Kill_Ratio,Combat_Sorties_Estimated
29,F/A-18F Block III,Boeing,USA,4.5,Multirole,2020,2022,1915,0,15240,...,0.70,0,0,NaN,0.0,0,0,Limited,NaN,2000
30,Su-30SM2,Sukhoi,Russia,4++,Multirole,2020,2022,2120,0,17300,...,0.50,0,0,NaN,0.0,0,0,Limited,NaN,2000
31,Rafale F4,Dassault,France,4.5,Multirole,2023,2024,1912,0,15835,...,0.80,0,0,NaN,0.0,0,0,NaN,NaN,0
32,J-10CE,Chengdu,China,4.5,Multirole,2020,2022,2200,0,18000,...,0.48,0,0,Limited,3.0,3,0,NaN,3.0,0
33,F-15SA,Boeing,USA/Saudi Arabia,4.5,Multirole,2013,2017,2655,0,20000,...,0.60,0,0,NaN,0.0,0,0,Limited,NaN,3000

In [21]:
fight_air.info()

<class 'pandas.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 45 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Aircraft                      34 non-null     str
 1   Manufacturer                  34 non-null     str
 2   Country                       34 non-null     str
 3   Generation                    34 non-null     str
 4   Role                          34 non-null     str
 5   First_Flight                  34 non-null     int64
 6   In_Service                    34 non-null     int64
 7   Max_Speed_kmh                 34 non-null     int64
 8   Supercruise_kmh               34 non-null     int64
 9   Service_Ceiling_m             34 non-null     int64
 10  Combat_Radius_km              34 non-null     int64
 11  Ferry_Range_km                34 non-null     int64
 12  Empty_Weight_kg               34 non-null     int64
 13  MTOW_kg                       34 non-null     int64
 14  Hardpoints                    34 non-null     int64
 15  Max_Weapon_Load_kg            34 non-null     int64
 16  Radar_Type                    34 non-null     str
 17  Radar_Model                   34 non-null     str
 18  RCS_m2                        34 non-null     float64
 19  Engine_Count                  34 non-null     int64
 20  Engine_Model                  34 non-null     str
 21  Thrust_per_Engine_kN          34 non-null     int64
 22  Supercruise_Capable           34 non-null     str
 23  Thrust_Vectoring              34 non-null     str
 24  Internal_Weapons_Bay          34 non-null     str
 25  Units_Produced                34 non-null     int64
 26  Unit_Cost_M_USD               34 non-null     int64
 27  Status                        34 non-null     str
 28  Internal_Fuel_kg              34 non-null     int64
 29  Fuel_Consumption_Cruise_kg_h  34 non-null     int64
 30  Number_of_Operators           34 non-null     int64
 31  Cruise_Speed_kmh              34 non-null     int64
 32  Cost_per_Flight_Hour_USD      34 non-null     int64
 33  Radar_Score                   34 non-null     float64
 34  Missile_Score                 34 non-null     float64
 35  EW_Score                      34 non-null     float64
 36  Combat_Kills                  34 non-null     int64
 37  Combat_Losses_AirToAir        34 non-null     int64
 38  Combat_Record_Status          18 non-null     str
 39  Kill_Loss_Ratio               34 non-null     float64
 40  Combat_Kills_A2A              34 non-null     int64
 41  Combat_Losses_A2A             34 non-null     int64
 42  Combat_Status                 22 non-null     str
 43  Kill_Ratio                    13 non-null     float64
 44  Combat_Sorties_Estimated      34 non-null     int64
dtypes: float64(6), int64(25), str(14)
memory usage: 12.1 KB

In [22]:
fight_air.describe

<bound method NDFrame.describe of                  Aircraft     Manufacturer           Country Generation  \
0            F-22A Raptor  Lockheed Martin               USA          5
1      F-35A Lightning II  Lockheed Martin               USA          5
2             Su-57 Felon           Sukhoi            Russia          5
3             F-15C Eagle           Boeing               USA          4
4         F-15EX Eagle II           Boeing               USA        4.5
5   F-16C Fighting Falcon  Lockheed Martin               USA          4
6    F/A-18E Super Hornet           Boeing               USA        4.5
7        Su-35S Flanker-E           Sukhoi            Russia        4++
8           Su-27 Flanker           Sukhoi            Russia          4
9          MiG-29 Fulcrum          Mikoyan            Russia          4
10        MiG-31 Foxhound          Mikoyan            Russia          4
11     J-20 Mighty Dragon          Chengdu             China          5
12  J-10C Vigorous Dragon          Chengdu             China        4.5
13  JF-17 Block 3 Thunder          CAC/PAC    China/Pakistan        4.5
14    Eurofighter Typhoon      Eurofighter            Europe        4.5
15        Dassault Rafale         Dassault            France        4.5
16    Saab JAS 39E Gripen             Saab            Sweden        4.5
17         HAL Tejas Mk1A              HAL             India          4
18          KF-21 Boramae              KAI       South Korea        4.5
19     F-15E Strike Eagle           Boeing               USA          4
20    Panavia Tornado ADV          Panavia            Europe          4
21           F-14D Tomcat          Grumman               USA          4
22          Mirage 2000-5         Dassault            France          4
23     Su-30MKI Flanker-H           Sukhoi      Russia/India        4.5
24        F-2A Viper Zero       Mitsubishi             Japan          4
25    Saab JAS 39C Gripen             Saab            Sweden         4+
26           J-16 Flanker         Shenyang             China        4.5
27       MiG-35 Fulcrum-F          Mikoyan            Russia        4++
28      F-16V Block 70/72  Lockheed Martin               USA        4.5
29      F/A-18F Block III           Boeing               USA        4.5
30               Su-30SM2           Sukhoi            Russia        4++
31              Rafale F4         Dassault            France        4.5
32                 J-10CE          Chengdu             China        4.5
33                 F-15SA           Boeing  USA/Saudi Arabia        4.5

               Role  First_Flight  In_Service  Max_Speed_kmh  Supercruise_kmh  \
0   Air Superiority          1997        2005           2130             1810
1         Multirole          2006        2016           1960                0
2         Multirole          2010        2020           2135             1400
3   Air Superiority          1972        1976           2655                0
4         Multirole          2021        2024           2655                0
5         Multirole          1974        1978           2120                0
6         Multirole          1995        2001           1915                0
7   Air Superiority          2008        2014           2500                0
8   Air Superiority          1977        1985           2500                0
9   Air Superiority          1977        1983           2400                0
10      Interceptor          1975        1981           3000                0
11  Air Superiority          2011        2017           2100                0
12        Multirole          1998        2018           2200                0
13        Multirole          2003        2007           1960                0
14        Multirole          1994        2003           2495             1530
15        Multirole          1986        2001           1912                0
16        Multirole          1988        2024           2205             1200
17        Multirole          2001        2016           1960                0
18        Multirole          2022        2026           1960                0
19        Multirole          1986        1989           2655                0
20      Interceptor          1979        1986           2340                0
21  Air Superiority          1970        1974           2485                0
22        Multirole          1978        1988           2340                0
23        Multirole          1996        2002           2120                0
24        Multirole          1995        2000           2124                0
25        Multirole          1988        1997           2205             1200
26        Multirole          2011        2015           2400                0
27        Multirole          2007        2019           2400                0
28        Multirole          2015        2024           2120                0
29        Multirole          2020        2022           1915                0
30        Multirole          2020        2022           2120                0
31        Multirole          2023        2024           1912                0
32        Multirole          2020        2022           2200                0
33        Multirole          2013        2017           2655                0

    Service_Ceiling_m  ...  EW_Score  Combat_Kills  Combat_Losses_AirToAir  \
0               15000  ...      0.95             0                       0
1               15240  ...      1.00             0                       0
2               20000  ...      0.75             1                       0
3               20000  ...      0.35           104                       0
4               20000  ...      0.70             0                       0
5               15240  ...      0.40            76                       5
6               15240  ...      0.65             1                       0
7               18000  ...      0.50             0                       1
8               18500  ...      0.20             6                      10
9               18000  ...      0.15             5                      27
10              20600  ...      0.45             0                       0
11              20000  ...      0.65             0                       0
12              18000  ...      0.45             0                       0
13              16920  ...      0.35             1                       0
14              19812  ...      0.70             0                       0
15              15835  ...      0.75             0                       1
16              15240  ...      0.65             0                       0
17              15240  ...      0.40             0                       0
18              16764  ...      0.50             0                       0
19              18200  ...      0.35             2                       2
20              15240  ...      0.25             0                       0
21              16150  ...      0.25             5                       0
22              17060  ...      0.35             3                       1
23              17300  ...      0.40             0                       1
24              15240  ...      0.40             0                       0
25              15240  ...      0.45             0                       0
26              17300  ...      0.50             0                       0
27              17500  ...      0.45             0                       0
28              15240  ...      0.55             0                       0
29              15240  ...      0.70             0                       0
30              17300  ...      0.50             0                       0
31              15835  ...      0.80             0                       0
32              18000  ...      0.48             0                       0
33              20000  ...      0.60             0                       0

    Combat_Record_Status  Kill_Loss_Ratio  Combat_Kills_A2A Combat_Losses_A2A  \
0                Limited         0.000000                 0                 0
1                Limited         0.000000                 0                 0
2                    NaN         0.000000                 0                 0
3              Extensive       104.000000               104                 0
4                    NaN         0.000000                 0                 0
5              Extensive        76.000000                76                 1
6                Limited         1.000000                 1                 0
7                Limited         0.000000                 0                 0
8                Limited         0.500000                 6                10
9              Extensive         0.181818                 4                24
10                   NaN         1.000000                 1                 0
11                   NaN         0.000000                 0                 0
12               Limited         3.000000                 3                 0
13               Limited         2.000000                 2                 0
14                   NaN         0.000000                 0                 0
15               Limited         0.000000                 0                 0
16                   NaN         0.000000                 0                 0
17                   NaN         0.000000                 0                 0
18                   NaN         0.000000                 0                 0
19             Extensive         2.000000                 2                 0
20               Limited         0.000000                 0                 0
21             Extensive         5.000000                 5                 0
22               Limited         2.000000                 2                 0
23               Limited         0.000000                 0                 0
24                   NaN         0.000000                 0                 0
25                   NaN         0.000000                 0                 0
26                   NaN         0.000000                 0                 0
27                   NaN         0.000000                 0                 0
28               Limited         0.000000                 0                 0
29                   NaN         0.000000                 0                 0
30                   NaN         0.000000                 0                 0
31                   NaN         0.000000                 0                 0
32               Limited         3.000000                 3                 0
33                   NaN         0.000000                 0                 0

   Combat_Status  Kill_Ratio  Combat_Sorties_Estimated
0        Limited         NaN                      2500
1        Limited    1.000000                      8000
2        Limited         NaN                       500
3      Extensive  104.000000                     50000
4            NaN         NaN                         0
5      Extensive   38.000000                    200000
6      Extensive    1.000000                     30000
7        Limited         NaN                      3000
8      Extensive    1.500000                     15000
9      Extensive    0.166667                     20000
10       Limited         NaN                      2000
11           NaN         NaN                         0
12       Limited         NaN                       500
13       Limited    3.000000                      2000
14       Limited         NaN                      5000
15     Extensive    0.000000                      8000
16           NaN         NaN                         0
17           NaN         NaN                         0
18           NaN         NaN                         0
19     Extensive    2.000000                     60000
20       Limited         NaN                     15000
21     Extensive    1.666667                     15000
22     Extensive    3.000000                     10000
23       Limited    0.000000                      3000
24           NaN         NaN                         0
25           NaN         NaN                         0
26           NaN         NaN                         0
27           NaN         NaN                         0
28           NaN         NaN                         0
29       Limited         NaN                      2000
30       Limited         NaN                      2000
31           NaN         NaN                         0
32           NaN    3.000000                         0
33       Limited         NaN                      3000

[34 rows x 45 columns]>

In [24]:
rows, cols = fight_air.shape
print(f'Rows: {rows}')
print(f'Cols: {cols}')

Rows: 34
Cols: 45

In [25]:
fight_air.columns

Index(['Aircraft', 'Manufacturer', 'Country', 'Generation', 'Role',
       'First_Flight', 'In_Service', 'Max_Speed_kmh', 'Supercruise_kmh',
       'Service_Ceiling_m', 'Combat_Radius_km', 'Ferry_Range_km',
       'Empty_Weight_kg', 'MTOW_kg', 'Hardpoints', 'Max_Weapon_Load_kg',
       'Radar_Type', 'Radar_Model', 'RCS_m2', 'Engine_Count', 'Engine_Model',
       'Thrust_per_Engine_kN', 'Supercruise_Capable', 'Thrust_Vectoring',
       'Internal_Weapons_Bay', 'Units_Produced', 'Unit_Cost_M_USD', 'Status',
       'Internal_Fuel_kg', 'Fuel_Consumption_Cruise_kg_h',
       'Number_of_Operators', 'Cruise_Speed_kmh', 'Cost_per_Flight_Hour_USD',
       'Radar_Score', 'Missile_Score', 'EW_Score', 'Combat_Kills',
       'Combat_Losses_AirToAir', 'Combat_Record_Status', 'Kill_Loss_Ratio',
       'Combat_Kills_A2A', 'Combat_Losses_A2A', 'Combat_Status', 'Kill_Ratio',
       'Combat_Sorties_Estimated'],
      dtype='str')